const rotas={};const MAIN_CONTENT_ID='spa-content';const REPO_BASE='/Ouvir-Cuidar-IV/';async function carregarConteudoDaRota(rotaNome){const caminhoCompleto=rotaNome==='index.html'?REPO_BASE:REPO_BASE+rotaNome;try{const response=await fetch(caminhoCompleto);if(!response.ok){throw new Error(`Erro ao carregar a página: ${response.statusText} (Caminho: ${caminhoCompleto})`)}
const html=await response.text();return html}catch(error){return `
            <section style="padding: 20px; text-align: center;">
                <h2>Erro de Carregamento</h2>
                <p>Não foi possível carregar a página solicitada.</p>
            </section>
        `}}
async function rotear(caminho,empurrarEstado=!0){let rotaNome=caminho;if(caminho.startsWith(REPO_BASE)){rotaNome=caminho.replace(REPO_BASE,'')}
if(rotaNome===''||rotaNome.endsWith('/'))rotaNome='index.html';let doc=null;if(!rotas[rotaNome]){const htmlCompleto=await carregarConteudoDaRota(rotaNome);const parser=new DOMParser();doc=parser.parseFromString(htmlCompleto,'text/html');const mainContent=doc.querySelector('main');if(mainContent){rotas[rotaNome]=mainContent.innerHTML}else{rotas[rotaNome]=`
                <section style="padding: 20px; text-align: center;">
                    <h2>Erro de Estrutura</h2>
                    <p>A página ${rotaNome} está incompleta ou sem a tag <main>.</p>
                </section>
            `}}else{const parser=new DOMParser();doc=parser.parseFromString(`<!DOCTYPE html><html><head><title></title></head><body><main>${rotas[rotaNome]}</main></body></html>`,'text/html')}
const contentElement=document.getElementById(MAIN_CONTENT_ID);if(contentElement){contentElement.innerHTML=rotas[rotaNome];if(empurrarEstado){const urlFinal=rotaNome==='index.html'?REPO_BASE:REPO_BASE+rotaNome;window.history.pushState({rota:rotaNome},'',urlFinal)}
const tituloDaPagina=doc.querySelector('title')?doc.querySelector('title').textContent:`Ouvir&Cuidar - ${rotaNome.replace('.html', '')}`;document.title=tituloDaPagina;executarScripts(rotaNome)}}
function aplicarTemplateSPA(){const mainElement=document.querySelector('main');if(mainElement){mainElement.id=MAIN_CONTENT_ID}}
function configurarDelegaçãoDeLinks(){document.body.addEventListener('click',function(e){const link=e.target.closest('a');if(link){const href=link.getAttribute('href');if(href&&href.endsWith('.html')&&!href.startsWith('http')&&!href.startsWith('mailto')){e.preventDefault();rotear(href)}}})}
function configurarAcessibilidade(){const body=document.body;const btnTema=document.getElementById("toggle-theme");const btnContraste=document.getElementById("toggle-contrast");function setTheme(theme){body.setAttribute("data-theme",theme);localStorage.setItem("theme",theme);if(btnTema)btnTema.textContent=theme==="dark"?"☀️":"🌙"}
const temaSalvo=localStorage.getItem("theme");const prefereEscuro=window.matchMedia("(prefers-color-scheme: dark)").matches;setTheme(temaSalvo||(prefereEscuro?"dark":"light"));if(btnTema){btnTema.addEventListener("click",()=>{const atual=body.getAttribute("data-theme");const novo=atual==="dark"?"light":"dark";setTheme(novo)})}
if(btnContraste){const contrasteAtivo=localStorage.getItem("highContrast")==="true";if(contrasteAtivo)body.classList.add("high-contrast");btnContraste.addEventListener("click",()=>{body.classList.toggle("high-contrast");const ativo=body.classList.contains("high-contrast");localStorage.setItem("highContrast",ativo?"true":"false")})}}
function executarScripts(rota){if(rota==='cadastro.html'){const cpfInput=document.getElementById('cpf');if(cpfInput&&!cpfInput.hasAttribute('data-mask-initialized-cpf')){cpfInput.setAttribute('data-mask-initialized-cpf','true');cpfInput.addEventListener('input',function(e){var value=e.target.value.replace(/\D/g,'');var formattedValue='';if(value.length>11){value=value.substring(0,11)}
if(value.length>9){formattedValue=value.substring(0,3)+'.'+value.substring(3,6)+'.'+value.substring(6,9)+'-'+value.substring(9,11)}else if(value.length>6){formattedValue=value.substring(0,3)+'.'+value.substring(3,6)+'.'+value.substring(6,9)}else if(value.length>3){formattedValue=value.substring(0,3)+'.'+value.substring(3,6)}else{formattedValue=value}
e.target.value=formattedValue})}
const telInput=document.getElementById('telefone');if(telInput&&!telInput.hasAttribute('data-mask-initialized-tel')){telInput.setAttribute('data-mask-initialized-tel','true');telInput.addEventListener('input',function(e){var value=e.target.value.replace(/\D/g,'');var formattedValue='';if(value.length>11){value=value.substring(0,11)}
if(value.length>10){formattedValue='('+value.substring(0,2)+') '+value.substring(2,7)+'-'+value.substring(7,11)}else if(value.length>6){formattedValue='('+value.substring(0,2)+') '+value.substring(2,6)+'-'+value.substring(6,10)}else if(value.length>2){formattedValue='('+value.substring(0,2)+') '+value.substring(2)}else{formattedValue=value}
e.target.value=formattedValue})}
const cepInput=document.getElementById('cep');if(cepInput&&!cepInput.hasAttribute('data-mask-initialized-cep')){cepInput.setAttribute('data-mask-initialized-cep','true');cepInput.addEventListener('input',function(e){var value=e.target.value.replace(/\D/g,'');var formattedValue='';if(value.length>8){value=value.substring(0,8)}
if(value.length>5){formattedValue=value.substring(0,5)+'-'+value.substring(5,8)}else{formattedValue=value}
e.target.value=formattedValue})}
configurarValidacaoFormulario()}}
function configurarValidacaoFormulario(){const form=document.querySelector('.formulario form');if(form){form.addEventListener('submit',function(e){e.preventDefault();let isValid=!0;document.querySelectorAll('.mensagem-erro').forEach(el=>el.remove());document.querySelectorAll('.erro-validacao').forEach(el=>el.classList.remove('erro-validacao'));function exibirErro(inputElement,mensagem){isValid=!1;inputElement.classList.add('erro-validacao');const erroElement=document.createElement('p');erroElement.classList.add('mensagem-erro');erroElement.setAttribute('role','alert');erroElement.textContent='❌ '+mensagem;inputElement.parentNode.insertBefore(erroElement,inputElement.nextSibling)}
const campos=form.querySelectorAll('input[required]');campos.forEach(input=>{if(!input.value.trim()){const labelText=input.previousElementSibling&&input.previousElementSibling.tagName==='LABEL'?input.previousElementSibling.textContent.replace(':','').trim():'Este campo';exibirErro(input,`${labelText} é obrigatório.`)}});const telefoneInput=document.getElementById('telefone');if(telefoneInput&&telefoneInput.value.trim()){const numLimpo=telefoneInput.value.replace(/\D/g,'');if(numLimpo.length<10||numLimpo.length>11){exibirErro(telefoneInput,'O Telefone/Celular deve incluir o DDD e ter 10 ou 11 dígitos.')}}
const emailInput=document.getElementById('email');const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(emailInput&&emailInput.value.trim()&&!emailPattern.test(emailInput.value)){exibirErro(emailInput,'Por favor, insira um e-mail válido.')}
const enderecoInput=document.getElementById('endereco');const cidadeInput=document.getElementById('cidade');const textoPattern=/[a-zA-Z].*[a-zA-Z].*[a-zA-Z]/;if(enderecoInput&&enderecoInput.value.trim()&&!textoPattern.test(enderecoInput.value)){exibirErro(enderecoInput,'O Endereço deve ser válido e conter pelo menos 3 letras.')}
if(cidadeInput&&cidadeInput.value.trim()&&!textoPattern.test(cidadeInput.value)){exibirErro(cidadeInput,'O nome da Cidade deve ser válido e conter pelo menos 3 letras.')}
const estadoInput=document.getElementById('estado');const estadoPattern=/^[a-zA-Z]{2}$/;if(estadoInput&&estadoInput.value.trim()&&!estadoPattern.test(estadoInput.value)){exibirErro(estadoInput,'O Estado deve ter exatamente 2 letras (Ex: SP).')}
const cepInput=document.getElementById('cep');const cepPattern=/^\d{5}-\d{3}$/;if(cepInput&&cepInput.value.trim()&&!cepPattern.test(cepInput.value)){exibirErro(cepInput,'O CEP deve estar no formato 00000-000.')}
const cpfInput=document.getElementById('cpf');const cpfPattern=/^\d{3}\.\d{3}\.\d{3}-\d{2}$/;if(cpfInput&&cpfInput.value.trim()&&!cpfPattern.test(cpfInput.value)){exibirErro(cpfInput,'O CPF deve estar completo e no formato 000.000.000-00.')}
const dataNascimentoInput=document.getElementById('dataNascimento');if(dataNascimentoInput&&dataNascimentoInput.value.trim()){const dataNascimento=new Date(dataNascimentoInput.value);const hoje=new Date();if(dataNascimento>hoje){exibirErro(dataNascimentoInput,'A data de nascimento não pode ser futura.')}else{let idade=hoje.getFullYear()-dataNascimento.getFullYear();const mes=hoje.getMonth()-dataNascimento.getMonth();if(mes<0||(mes===0&&hoje.getDate()<dataNascimento.getDate())){idade--}
if(idade<18){exibirErro(dataNascimentoInput,'É necessário ter no mínimo 18 anos para se cadastrar.')}}}
if(isValid){alert("✅ Cadastro enviado com sucesso! Entraremos em contato.");form.reset()}else{const primeiroErro=document.querySelector('.mensagem-erro');if(primeiroErro){const inputComErro=primeiroErro.previousElementSibling;if(inputComErro){inputComErro.focus()}
primeiroErro.scrollIntoView({behavior:'smooth',block:'center'})}}})}}
window.addEventListener('popstate',(e)=>{const rotaCorrigida=e.state&&e.state.rota?e.state.rota:'index.html';rotear(rotaCorrigida,!1)});document.addEventListener('DOMContentLoaded',()=>{aplicarTemplateSPA();configurarDelegaçãoDeLinks();configurarAcessibilidade();const caminhoAtual=window.location.pathname;let caminhoInicial='index.html';if(caminhoAtual.includes(REPO_BASE)){const partes=caminhoAtual.split('/');caminhoInicial=partes.pop()||'index.html'}
rotear(caminhoInicial,!1)})
